//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSGImpressionConn.Web.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarberDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BarberDetail()
        {
            this.AppointmentDetails = new HashSet<AppointmentDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int Phone { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> BarberTypeID { get; set; }
        public Nullable<int> ShopDetailID { get; set; }
    
        public virtual BarberType BarberType { get; set; }
        public virtual ShopDetail ShopDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentDetail> AppointmentDetails { get; set; }
    }
}
